### ISSUE TITLE
Hm maybe make the nsfw links and scam links seperate? Just a suggestion.

### ISSUE THREAD

**Issue by LightningBolt62** [elbkr/bad-websites#4]

**Comment by elbkr** [comment]
I will make it now.

**Comment by LightningBolt62** [comment]
> I will make it now.

Awesome

**Comment by elbkr** [comment]
But you were thinking on separated files or separate them in the `websites.json` file with comments?
Like 
// nsfw sites
"badwebsitensfw.com",
"supernsfwsite.com",
// pirate sites
"piratesite.com"

**Comment by LightningBolt62** [comment]
> But you were thinking on separated files or separate them in the `websites.json` file with comments?
> Like
> This is separate with comments:
> // nsfw sites
> "badwebsitensfw.com",
> "supernsfwsite.com",
> // pirate sites
> "piratesite.com"

Seperate files because bots can't read comments

**Comment by elbkr** [comment]
Oh, what do you want to do with them?

**Comment by LightningBolt62** [comment]
> Oh, what do you want to do with them?

My bot has a `;screenshot` command to provide screenshots of websites. Basically i want to block it if someone tries to screenshot an nsfw site without being in an nsfw channel.
